name: HACS validation
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"
